language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - packages/lager/node_modules
    - packages/cli/node_modules
    - packages/iam/node_modules
    - packages/node-lambda/node_modules
    - packages/api-gateway/node_modules
install:
  - bash travis-install.sh
# Matrix begin
node_js:
  - "6"
  - "4"
env:
  - TEST_SUITE=integration
  - TEST_SUITE=lager
  - TEST_SUITE=cli
  - TEST_SUITE=iam
  - TEST_SUITE=node-lambda
  - TEST_SUITE=api-gateway
# Matrix end
script:
  - bash travis-run.sh
